import React from "react";
import  "./styles.scss";
import "./script.js"
function Custom() {


  
  return <div id="site">
  <div id="player">
    <div className="player">
      <div className="player__video">
        {/* Current video is for reference only. It will be generated by JavaScript code. */}
        <iframe id="current-video" width={560} height={315} src="https://www.youtube.com/embed/BWIPZvwcnX8" frameBorder={0} allow="autoplay; encrypted-media" allowFullScreen />
      </div>
    </div>
  </div>
  <div id="gallery">
    <div className="gallery">It will be generated by JavaScript code.</div>
  </div>
</div>
;
}

export default Custom;